Feature/115 improve dnd
csesoc/notangles pull request #121
Opened 2020-07-14 04:15 UTC by lukefisklennon

2020-10-11 06:56 UTC, lukefisklennon commented
This PR replaces `react-dnd` with a custom drag-and-drop implementation.

Features include:

- Cross-platform consistency
- Eliminates image flicker
- No longer a need for naive native image clipping
- Better styling (replaces ghosting with depth and shadow effects)
- Animation (when mounting, unmounting and dragging)
- Live state preview as you drag
- Uses intersection area instead of cursor position when dropping (easier to use by Fitts's law)
- Basic touch support (hold-to-drag will be added later)
- Enable mouse wheel scrolling while dragging (auto-scrolling will be added later)

Some issues:

- Due to the performance constraints presented by live preview, and due to styled components [being slow](https://github.com/styled-components/styled-components/issues/2215), a few styled components have been converted to style objects (but are still semantically similar)
- Also, most components are now memoised by custom comparison functions, which may avoid false positives by looking deeper than referential identity; this is something to keep in mind as it may cause bugs with components not re-rendering, so we may want to remove these custom comparators at some point

2020-10-17 04:03 UTC, maxwowo requested changes
Damn this is some insane stuff, well freaking done 🔥

2020-10-17 05:52 UTC, lukefisklennon commented on client/src/components/CourseSelect.tsx
> +};
Ah yeah good catch, not sure why that's there

2020-10-17 09:20 UTC, maxwowo approved these changes
Noice
![image](https://user-images.githubusercontent.com/40416283/96333517-23769b80-10b6-11eb-9fbd-9a90d863757a.png)

2020-10-17 09:26 UTC, merged