Feature/116 store timetable locally
csesoc/notangles pull request #141
Opened 2020-10-25 08:28 UTC by lukefisklennon

Stores the selected courses and timetable data locally

2020-10-31 04:44 UTC, maxwowo commented
I'm getting this error screen after selecting a course, closing the tab, then reopening `localhost:3000`
![image](https://user-images.githubusercontent.com/40416283/97771336-df909580-1b8f-11eb-9eff-6808676da965.png)

2020-10-31 04:54 UTC, lukefisklennon commented
That's so strange, I was getting that issue too, then it went away for a while, now it's back 🤔 I'll look into it now

2020-10-31 05:04 UTC, maxwowo commented
> That's so strange, I was getting that issue too, then it went away for a while, now it's back 🤔 I'll look into it now

Oof that's tough to debug, below is exactly what I did, maybe it'll help
1. npm run start:mock
2. Choose COMP9243
3. Close tab
4. Reopen localhost:3000

2020-10-31 06:32 UTC, lukefisklennon commented
> Oof that's tough to debug, below is exactly what I did, maybe it'll help

Ah thanks, as it turns out the bug would happen if there was high enough network latency, so it appeared to happen at random. Should be fixed now.

2020-10-31 09:52 UTC, maxwowo requested changes
Just a minor remark, everything else looks good

2020-10-31 11:09 UTC, lukefisklennon commented on client/src/App.tsx
> +};
Ah yes, good idea

2020-11-01 00:52 UTC, maxwowo approved these changes

2020-11-01 03:54 UTC, esyw approved these changes

2020-11-01 04:09 UTC, merged