Fixed course start and end times
csesoc/notangles pull request #185
Opened 2021-06-16 06:13 UTC by emilytangg

2021-06-16 10:22 UTC, oliverxu42 approved these changes
Looks good!

2021-06-16 14:04 UTC, lukefisklennon requested changes
Nice work! There's just one issue with how the start and end times are being rounded:

![image](https://user-images.githubusercontent.com/43358885/122232425-91ea5280-cefe-11eb-934e-1627524c4596.png)

Because the end time is floored instead of ceiling'd, there's half a row less than what's needed. Same for the start time, so the floor and ceiling can just be swapped.

2021-06-17 01:42 UTC, emilytangg commented
> Nice work! There's just one issue with how the start and end times are being rounded:
> 
> ![image](https://user-images.githubusercontent.com/43358885/122232425-91ea5280-cefe-11eb-934e-1627524c4596.png)
> 
> Because the end time is floored instead of ceiling'd, there's half a row less than what's needed. Same for the start time, so the floor and ceiling can just be swapped.

Oops my bad, I will fix this :)

2021-06-17 05:00 UTC, lukefisklennon approved these changes

2021-06-19 05:00 UTC, merged