Feature/ntgl 261 settings modal
csesoc/notangles pull request #205
Opened 2022-02-26 03:55 UTC by emilytangg

- Moved existing settings for dark mode and 12h time format to the settings modal
- Added setting to hide classes at full capacity
- Added setting to move newly added classes to the Unscheduled column by default
- Minor changes to styling of settings modal
- Added "compact mode" setting which hides class information

2022-02-28 10:00 UTC, oliverxu42 commented
Wait when you select a course there's no more fade in?

2022-03-02 04:45 UTC, munjoonteo commented on client/src/components/Settings.tsx
> +    const settingsToggles: { state: boolean; setter: (mode: boolean) => void; desc: string }[] = [
We are probably going to do something with all these random type declarations floating around some day... I'd prefer them to be in their own file

2022-03-02 04:46 UTC, munjoonteo requested changes

2022-03-02 04:46 UTC, munjoonteo commented on client/src/components/Settings.tsx
> +              value={e['state']}
Can you call this something other than `e` please

2022-03-02 04:46 UTC, munjoonteo commented on client/src/components/Settings.tsx
> +      { state: isHideClassInfo, setter: setIsHideClassInfo, desc: 'Hide class information' },
Hide detailed class information instead?

2022-03-05 06:29 UTC, oliverxu42 approved these changes
Good stuff!

2022-03-05 07:04 UTC, munjoonteo approved these changes

2022-03-05 07:06 UTC, merged