Change enrolled text to red when class full
csesoc/notangles pull request #206
Opened 2022-02-26 05:26 UTC by maxphillipsdev

bottom text

2022-02-27 05:17 UTC, munjoonteo requested changes

2022-02-27 05:17 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +        style={{
No inline styles please. Turn this into a styled component.

2022-02-27 05:17 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +import { orange, red } from '@material-ui/core/colors';
Unused import `orange`?

2022-02-27 05:17 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +interface PeriodMetadataProps {
The interfaces scattered throughout the file make me sad :(( Do you think it's cleaner to put all the interfaces, especially for proptypes, into something like `src/types/props.ts`?

2022-03-02 12:39 UTC, blueybloke commented on client/src/components/timetable/DroppedClasses.tsx
> +interface PeriodMetadataProps {
They make me sad too :(( I usually like to keep any prop interfaces above the component they are used for and then have a types folder for any shared typings. I think consolidating the typings in the project would prob be another ticket tho, did it here since I saw it was the pattern used on the other components in this file.

2022-03-03 02:34 UTC, munjoonteo approved these changes

2022-03-03 09:41 UTC, oliverxu42 commented
![image](https://user-images.githubusercontent.com/81744880/156538385-af50ca50-e3b5-4c6e-96ac-ec8ab15377d9.png)

2022-03-07 02:35 UTC, munjoonteo requested changes

2022-03-07 02:35 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +  const EnrolledIndicator = styled.span`
This is not used anymore?

2022-03-07 02:35 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    font-weight: ${percentEnrolled === 1 ? 'bolder' : undefined};
Think you need a `margin: 0;` here. Should fix the weird spacing shenanigans.

2022-03-08 09:55 UTC, maxphillipsdev commented
@munjoonteo @oliverxu42 PR reviewey-wuey pleasey-weasy? 🥺👉👈

2022-03-08 09:59 UTC, munjoonteo approved these changes

2022-03-08 10:03 UTC, oliverxu42 approved these changes

2022-03-08 10:04 UTC, merged