Feature/ntgl 271 course delivery mode icons
csesoc/notangles pull request #243
Opened 2022-03-17 03:05 UTC by emilytangg

- Removed the in-person course filter tabs
- Made the delivery mode icons correspond to course data

2022-03-17 04:37 UTC, munjoonteo requested changes

2022-03-17 04:37 UTC, munjoonteo commented on client/src/components/CourseSelect.tsx
> +import VideocamOutlinedIcon from '@material-ui/icons/VideocamOutlined';
These two imports can be included in the import from `@material-ui/icons` on line 5

2022-03-17 04:37 UTC, munjoonteo commented on client/src/components/CourseSelect.tsx
> +
Random spaces?

2022-03-17 04:37 UTC, munjoonteo commented on server/src/controllers/getCourse.ts
> +  console.log(course)
No `console.log()`s please

2022-03-17 05:02 UTC, emilytangg commented on client/src/components/CourseSelect.tsx
> +
Ah I'm not sure why it's like that, will be more careful in future.

2022-03-17 05:54 UTC, munjoonteo commented on client/src/components/CourseSelect.tsx
> +
Prettier should get rid of it for you - have you set `Auto Save` to be `afterDelay` and `Format on Save` to be `true` and `Default Formatter` to be `Prettier` in your VSCode?

2022-03-18 00:53 UTC, emilytangg commented on client/src/components/CourseSelect.tsx
> +
Ahh I forgot to do those things after I installed the Prettier extension, thanks MJ!

2022-03-18 10:40 UTC, munjoonteo approved these changes

2022-03-18 10:58 UTC, oliverxu42 approved these changes

2022-03-18 11:08 UTC, merged