Feature/ntgl 280 differentiate ug pg
csesoc/notangles pull request #283
Opened 2022-03-27 10:53 UTC by oliverxu42

Adds an indicator to show if the course is under/post grad.

![image](https://user-images.githubusercontent.com/81744880/160278061-918982ec-e263-4bb6-8db6-d7fcb386ec06.png)

2022-03-27 12:07 UTC, munjoonteo requested changes

2022-03-27 12:07 UTC, munjoonteo commented on client/src/components/CourseSelect.tsx
> +            <Career>{option.career}</Career>
What do you think about making it just UG or PG instead of "Undergraduate" and "Postgraduate"

2022-03-27 23:41 UTC, oliverxu42 commented on client/src/components/CourseSelect.tsx
> +            <Career>{option.career}</Career>
Yeah true I think UNSW abbreviates to UGRD/PGRD so that might be better.

2022-03-28 01:16 UTC, munjoonteo approved these changes

2022-03-28 01:17 UTC, merged