History
csesoc/notangles pull request #292
Opened 2022-03-30 04:36 UTC by martanman

with fixes for theme and breakpoints

2022-03-30 04:55 UTC, oliverxu42 approved these changes

2022-03-31 01:02 UTC, munjoonteo requested changes

2022-03-31 01:02 UTC, munjoonteo commented on client/src/components/CourseSelect.tsx
> +            return (
Why the explicit `return`?

2022-03-31 03:01 UTC, martanman commented on client/src/components/CourseSelect.tsx
> +            return (
no reason

2022-03-31 08:50 UTC, merged