new branch for sentry setup
csesoc/notangles pull request #321
Opened 2022-04-13 03:07 UTC by OAK-02

Didnt get time to resolve the merge conflicts so just made a new pull request. :)
(Added in sentry for the autotimetable as well)

2022-04-13 03:18 UTC, munjoonteo requested changes

2022-04-13 03:18 UTC, munjoonteo commented on client/src/index.tsx
> +  dsn: 'https://e4555a736f024545bef4a45873315f6a@o1179870.ingest.sentry.io/6292248',
Env variable here

2022-04-13 03:18 UTC, munjoonteo commented on auto_server/server.py
> +    "https://4befe4d099314fec8e5283e484abf431@o1179870.ingest.sentry.io/6327124",
Environment variable here

2022-04-13 03:19 UTC, munjoonteo commented
Also add Sentry in the `/server` file

2022-04-26 02:10 UTC, munjoonteo approved these changes

2022-04-26 05:21 UTC, oliverxu42 approved these changes

2022-04-26 08:08 UTC, merged