Ntgl 269 setup login api
csesoc/notangles pull request #337
Opened 2022-04-18 06:24 UTC by maxphillipsdev

2022-05-15 12:51 UTC, munjoonteo requested changes

2022-05-15 12:51 UTC, munjoonteo commented on backend.md
> +# Backend docs
Can you make this README into something similar to the old README? I'd like to keep the format consistent for all the READMEs.

2022-05-15 12:51 UTC, munjoonteo commented on backend.md
> +## Enviornment variables Required
The env vars can go straight into the Confluence.

2022-05-16 13:23 UTC, maxphillipsdev commented on backend.md
> +## Enviornment variables Required
[](https://compclub.atlassian.net/l/c/9QDiMnxN)

2022-05-20 01:16 UTC, munjoonteo approved these changes

2022-05-20 01:19 UTC, merged