Feature/ntgl 309 fix timetable clash bugs
csesoc/notangles pull request #346
Opened 2022-04-19 14:11 UTC by gracexkan

2022-04-23 01:06 UTC, munjoonteo requested changes

2022-04-23 01:06 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    // Sort clashes into a list of lists, where each smaller list
Probably can rewrite this comment to better explain what's going on.

2022-04-23 01:06 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    // groupedClashes is a list of days
Fix this one up too

2022-04-23 01:06 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    /*
Is this comment necessary? Maybe add a bit more detail to the `groupedClashes` and `getCardWidth` functions

2022-04-23 01:06 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +export const days: string[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
Instead of using this array, can you use the days declared in the context?

2022-04-23 01:27 UTC, gracexkan commented on client/src/constants/timetable.ts
> +export const days: string[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
yep I've made the context and comment changes

2022-04-23 02:27 UTC, munjoonteo requested changes

2022-04-23 02:27 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +  if (isPeriod(cardData) && clashIndex !== undefined && width) {
Is it necessary to check that `clashIndex !== undefined`? Does just `&& clashIndex && width` work?

2022-04-23 02:27 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> -  outline: ${({ hasClash }) => (hasClash ? 'solid red 4px' : 'solid transparent 0px')};
We weren't gonna keep the outline? Were you going to implement different outline colours for permitted and non-permitted clashes?

2022-04-23 02:27 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    const days = useContext(AppContext).days;
Instead of declaring the `useContext` here, you can declare above the `useContext(CourseContext)` at line 395 to avoid repeating code

2022-04-23 02:27 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    // Object.values(sortedClashes).forEach((clashes) => clashes.sort((a, b) => a.time.start - b.time.start));
Delete this comment

2022-04-23 02:28 UTC, munjoonteo commented
Also I missed this in an earlier PR but delete the comma on line 93 in the `hover` part of the `ExpandButton` styled component. Don't forget to lint your code! Is Prettier set up properly?

2022-04-23 03:15 UTC, gracexkan commented on client/src/components/timetable/DroppedClasses.tsx
> -  outline: ${({ hasClash }) => (hasClash ? 'solid red 4px' : 'solid transparent 0px')};
ye I'll be doing that tonight along with trying to fix that whack bug with the z-indexes

2022-04-29 00:16 UTC, martanman commented
![image](https://user-images.githubusercontent.com/22385238/165867287-b914f8e1-0956-4416-b27e-d83c00370cc6.png)
if this is a bug it doesn't seem to be fixed yet

2022-05-12 23:19 UTC, gracexkan commented
> ![image](https://user-images.githubusercontent.com/22385238/165867287-b914f8e1-0956-4416-b27e-d83c00370cc6.png) if this is a bug it doesn't seem to be fixed yet

whoops didn't see this earlier - I'll try fixing that

2022-05-16 03:17 UTC, oliverxu42 approved these changes

2022-05-26 12:47 UTC, munjoonteo requested changes

2022-05-26 12:47 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
This file is wayy too big now. Can you split it up into `DroppedClass` and `DroppedClasses`

2022-05-26 12:47 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    // const points = [40, 100, 1, 5, 25, 10];
No random comments in prod please XD

2022-05-26 12:47 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +  if ('time' in cardData) {
This entire `if` block basically changes the `clashColour` of the class right? Why don't you put this logic into the `DroppedClasses` component then just pass down the correct `clashColour`? It would probably reduce the complexity of the algorithm as well because with the current algorithm you are traversing the entire `groupedClashes` array per `cardData` to find the correct `clashGroup`.

2022-05-26 12:47 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
>  `;
I don't know how the comma at the end of line 101 is still here but can you get rid of it please.

2022-06-11 09:08 UTC, munjoonteo approved these changes

2022-06-11 09:13 UTC, merged