gave algo objective to maximize enforced constraints
csesoc/notangles pull request #364
Opened 2022-04-21 08:06 UTC by martanman

Affects days of the week of classes (i.e mad days of uni) and earliest start times and latest end time constraints

2022-04-22 05:59 UTC, munjoonteo commented
I should've pointed this out before but for multiplying everything by 2, can you make that a constant instead of a magic number? And explain in a comment that you need to scale it to get rid of half hours.

Also why do you need to multiply by 100 on lines 123 and 124?

2022-04-22 06:08 UTC, martanman commented
@munjoonteo i * 100 indicates the start of day i, as time are given as DotW * 100 + timeOfDay.
ok i will make 2 a constant (even though nothing is a constant in python but yes if u mean big capital letters global variable then oki)

2022-04-22 06:15 UTC, munjoonteo commented
Oh that makes sense ok

2022-04-22 10:12 UTC, munjoonteo commented
Do you think we should let the user know that not all of their constraints have been satisfied? Maybe a yellow coloured alert or something

2022-04-22 10:46 UTC, martanman commented
@munjoonteo I've considered it, and possibly, but not totally sure, and not sure what exactly the message should say. it _may_ in fact be implicit (or may not) that the autotimetabler does the best it can, or perhaps even more likely, it may not even be conceptualised as constraint-based by the user.
would the average person expect it to strictly adhere to their constraints?

but yeah sure tbh.

2022-04-23 01:01 UTC, munjoonteo commented
Hmm I guess it depends on how blatant the violation is right... like say if I said no earlier than 12pm and it gives me an 11am class then sure I could live with that. But if I say no Fridays and it gives me a Friday class I'm like ????

I guess the message could say something along the lines of "Not all requirements satisfied"?

2022-04-29 08:46 UTC, munjoonteo requested changes

2022-04-29 08:46 UTC, munjoonteo commented on client/src/components/Alerts.tsx
> +    return alertMsg === 'Success!' ? 'success' : alertMsg.startsWith('Could not') ? 'warning' : 'error';
At this point it's probably more readable to have it as a switch statement right?

2022-04-29 11:25 UTC, martanman commented on client/src/components/Alerts.tsx
> +    return alertMsg === 'Success!' ? 'success' : alertMsg.startsWith('Could not') ? 'warning' : 'error';
i _was_ considering it but lowkey switch statements are yucky boilerplate. plus it would mean having to write out the full message instead of having the string.startsWith()

2022-05-13 11:12 UTC, munjoonteo approved these changes

2022-05-13 11:17 UTC, merged