Ntgl 303 automate first day
csesoc/notangles pull request #409
Opened 2022-06-03 07:02 UTC by Rayahhhmed

Can I get a Code review for this as well, thought made a PR for it :(

2022-06-03 08:44 UTC, munjoonteo requested changes

2022-06-03 08:44 UTC, munjoonteo commented on client/src/App.tsx
> +
Prettier?

2022-06-03 08:44 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +
Prettier again

2022-06-03 08:44 UTC, munjoonteo commented on client/src/api/getCoursesList.ts
> +    console.log(baseURL, json);
No console logs in prod XD

2022-06-03 08:44 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +    if (matched != null) {
If I wrote this if block I'd put it all on one line, up to you if you want to change it.

2022-06-03 08:44 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +      termNumber = 0; // This is a summer term.
Don't need the duplicate comment here

2022-06-03 08:44 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +    return {
If you are just going to return the term data, do they need to be:
1. initialised at the top of the file
2. marked as `export`?

2022-06-03 08:44 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +    console.log('Could not ping timetable scraper!');
So what happens if there is an error? Should we return something meaningful to the user?

2022-06-03 08:44 UTC, munjoonteo commented on client/src/constants/timetable.ts
> -  '#8AC352', // light green
What happened here?

2022-06-03 08:44 UTC, munjoonteo commented on client/src/index.tsx
> +  ReactDOM.render(<Root />, document.getElementById('root'));
What happens to `res`?

Instead of doing this I think you should call `setAvailableTermDetails` in `App.tsx` then chuck the term data and whatnot into the context store instead. I don't like how you've changed `index.tsx` it looks weird to have API calls in this file.

2022-06-03 08:44 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +    const termIdFetch = await timeoutPromise(1000, fetch(`${API_URL.timetable}/availableterm`));
This should be declared closer to where it is used, i.e. line 28

2022-06-04 07:02 UTC, Rayahhhmed commented on client/src/index.tsx
> +  ReactDOM.render(<Root />, document.getElementById('root'));
I tried something similar before, but for some reason, All the courses were being selected by default..? That's why i was like i just need the term data before anything happens

2022-06-09 23:24 UTC, Rayahhhmed commented on client/src/index.tsx
> +  ReactDOM.render(<Root />, document.getElementById('root'));
Would it be possible for you to just check if you are okay with the way I handled conditional rendering in App now ?

2022-06-16 14:47 UTC, Rayahhhmed commented
@munjoonteo can you please check the pr

2022-06-18 12:02 UTC, munjoonteo requested changes

2022-06-18 12:02 UTC, munjoonteo commented on client/src/App.tsx
> +  useUpdateEffect(() => {
This should be useEffect

2022-06-18 12:02 UTC, munjoonteo commented on client/src/components/controls/CourseSelect.tsx
> +  }, [year]);
Did we agree to remove this year param

2022-06-18 12:02 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +export const setAvailableTermDetails = async () => {
Can this function be called `getAvailableTermDetails`

2022-06-18 12:02 UTC, munjoonteo commented on client/src/context/AppContext.tsx
> +  const [term, setTerm] = useState(`T0`);
Ok you make the choice here. Either remove all the explicit type annotations of the useState in the ones above, or add explicit type annotations for all the useStates from `lastUpdated` onwards

2022-06-18 12:02 UTC, munjoonteo commented on client/src/index.tsx
> +  <>
No empty `<></>` here

2022-06-18 12:02 UTC, munjoonteo commented on client/src/utils/generateICS.ts
> +import { AppContext } from '../context/AppContext';
Can you run `alt + shift + o` to sort the imports here

2022-06-18 12:02 UTC, munjoonteo commented on client/src/utils/generateICS.ts
> +  const currDate = dayjs(useContext(AppContext)!.firstDayOfTerm + `T00:00:00.000Z`)
I'd like the useContext to be outside the function. Destructure `firstDayOfTerm` from the `AppContext`

2022-06-18 12:23 UTC, Rayahhhmed commented on client/src/components/controls/CourseSelect.tsx
> +  }, [year]);
We did, but since our original app context stores the invalid data for the stuff, I run this useEffect hook so that i fire the course list fetch after our term data promise is retrieved. Removing it should break things

2022-06-18 14:20 UTC, munjoonteo commented on client/src/components/controls/CourseSelect.tsx
> +  }, [year]);
Makes sense

2022-06-20 13:14 UTC, munjoonteo approved these changes

2022-06-21 00:48 UTC, merged