changed translatex to make cards look cleaner when arranged
csesoc/notangles pull request #426
Opened 2022-06-14 04:43 UTC by martanman

before:
![chrome_VHkS6A6Lxh](https://user-images.githubusercontent.com/22385238/173493665-f73aceea-fce6-4d8f-a90c-7b002064defb.png)
![chrome_NhJJUxkjDT](https://user-images.githubusercontent.com/22385238/173493683-b9bb15d6-5f9c-4917-a8d6-a1ad3a0ae621.png)
![chrome_pCSBXm5kZI](https://user-images.githubusercontent.com/22385238/173494178-0ddde0ca-0da5-4e82-a91b-28db0ef58042.png)
![image](https://user-images.githubusercontent.com/22385238/173494607-e6b9a36a-c904-410b-a157-472b1f4a26d8.png)

after:
![chrome_ZIqDMxqoP6](https://user-images.githubusercontent.com/22385238/173493696-8857cba3-8f02-4b3b-b4a9-1d9ac049dbcf.png)
![chrome_AirhCpsZ9e](https://user-images.githubusercontent.com/22385238/173493711-e4d56a44-86d9-44b1-a2cc-19e181581f54.png)
![chrome_qck16VbNv9](https://user-images.githubusercontent.com/22385238/173494194-982738a1-0807-4b7e-8a65-e52e0f90f3ec.png)
![image](https://user-images.githubusercontent.com/22385238/173494593-dd38c283-8e8a-4370-817c-504c239881d4.png)

2022-06-14 10:14 UTC, munjoonteo requested changes

2022-06-14 10:14 UTC, munjoonteo commented on client/src/interfaces/PropTypes.ts
> +  recWidth: number; // width of a grid cell
can u call this `cellWidth` lol

2022-06-14 10:14 UTC, munjoonteo commented on client/src/components/timetable/DroppedClasses.tsx
> +    function updateRecWidth() {
no declaring functions with the `function` keyword

2022-06-14 10:14 UTC, munjoonteo commented on client/src/components/timetable/DroppedClass.tsx
> -  border-radius: ${({ isSquareEdges }) => (isSquareEdges ? '0px' : '7px')};
rest in pieces square corners. did u mean to delete this?

2022-06-14 12:20 UTC, martanman commented on client/src/components/timetable/DroppedClasses.tsx
> +    function updateRecWidth() {
when I copy code from stack overflow and I'm scared it won't work unless I copy it exactly

2022-06-14 12:39 UTC, martanman commented on client/src/components/timetable/DroppedClass.tsx
> -  border-radius: ${({ isSquareEdges }) => (isSquareEdges ? '0px' : '7px')};
yup, https://mui.com/material-ui/api/paper/ paper has prop `square`.

2022-06-15 14:20 UTC, munjoonteo approved these changes

2022-06-15 14:24 UTC, munjoonteo requested changes

2022-06-15 14:24 UTC, munjoonteo commented on client/src/components/timetable/DroppedClass.tsx
>    // 5 / devicePixelRatio refers to the five timetable borders between Monday and the Unscheduled column
Can you update this comment please

2022-06-15 14:24 UTC, munjoonteo commented on client/src/components/timetable/DroppedClass.tsx
> +    return `${(cellWidth + 1) * (cardData.time.day - 1) + clashIndex * (cellWidth / widthRatio)}px`;
Some explanation here would be nice

2022-06-15 14:29 UTC, martanman commented on client/src/components/timetable/DroppedClass.tsx
> +    return `${(cellWidth + 1) * (cardData.time.day - 1) + clashIndex * (cellWidth / widthRatio)}px`;
thought it was kinda self explanatory but sure

2022-06-16 12:00 UTC, munjoonteo approved these changes

2022-06-16 12:03 UTC, merged