Feature/ntgl 334 consolidate overlapping period info into one period
csesoc/notangles pull request #465
Opened 2022-07-15 13:35 UTC by gracexkan

Before:

<img width="1387" alt="Screen Shot 2022-07-15 at 11 33 04 pm" src="https://user-images.githubusercontent.com/80564637/179233766-32821c22-7e70-4408-aed0-554d50e6263f.png">
<img width="1374" alt="Screen Shot 2022-07-15 at 11 33 08 pm" src="https://user-images.githubusercontent.com/80564637/179233864-4e05edaf-a807-4aa7-9db6-da45a81dd9e0.png">

After:
<img width="1373" alt="Screen Shot 2022-07-15 at 11 33 11 pm" src="https://user-images.githubusercontent.com/80564637/179233918-c96c75aa-8bc5-4903-9dad-899416a73dde.png">

2022-07-15 14:11 UTC, munjoonteo commented
![image](https://user-images.githubusercontent.com/46366143/179240783-30c88311-498a-4033-b196-8d814f060d70.png)
What is this o.o

2022-07-16 02:27 UTC, munjoonteo requested changes

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +  for (let k = 0; k < dbClassWeeks.length; k++) {
This reads a lot like C - in Python I would write this entire loop with the `enumerate` keyword. Can you find an equivalent in JS?

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +  arr = arr.sort(function (a, b) {
`const` syntax for functions please

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +        for (let i = 0; i < dbClass.times.length - 1; i += 1) {
Given the context of this PR I understand what this code is doing but someone reading this for the first time would probably have no idea why this is necessary. Can you add a comment?

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +              dbClassTimesOne.day == dbClassTimesTwo.day &&
This could probably be a function

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +  return dbClassTimesList;
Javascript objects are always (ok well not technically) passed by reference. You don't need to return the new list.

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +const sortUnique = (arr: number[]): number[] => {
You should've copied this so thread instead https://stackoverflow.com/questions/1960473/get-all-unique-values-in-a-javascript-array-remove-duplicates XD

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +              for (let k = 0; k < dbClassTimesList.length; k++) {
This can also use the same `enumerate` replacement you created in `convertTimesToList`

2022-07-16 02:27 UTC, munjoonteo commented on client/src/api/getCourseInfo.ts
> +    });
New line here would be nice

2022-07-22 14:56 UTC, gracexkan commented on client/src/api/getCourseInfo.ts
> +  for (let k = 0; k < dbClassWeeks.length; k++) {
@munjoonteo I've used a for loop here because I do k++ inside the loop sometimes, can the equivalent still do that?

2022-07-23 01:33 UTC, oliverxu42 approved these changes

2022-07-23 01:37 UTC, munjoonteo approved these changes

2022-07-23 01:40 UTC, merged