Feature/ntgl 251 custom user events
csesoc/notangles pull request #466
Opened 2022-07-15 14:53 UTC by sssijin

thank you kind lord and saviour mj, please close the door on custom events

2022-07-16 01:59 UTC, munjoonteo requested changes

2022-07-16 01:59 UTC, munjoonteo commented on client/src/App.tsx
> +      if (event[1].time.day === 6 && days.length != 7) {
What is `event[1]`

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/controls/Autotimetabler.tsx
> +const StyledList = styled(List)`
This style is shared with the create custom event dropdown. Can you grab it from the shared styles file and see if it still looks good?

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/controls/CustomEvents.tsx
> +  //if trye, the popover is shown, currently set to the same as anchorEL
Typo

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/controls/CustomEvents.tsx
> +    <div style={{ display: 'flex' }}>
Remove this inline style please. It's the same in Autotimetabler so can you put it in a shared style file along with the StyledList I mentioned above.

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/controls/History.tsx
> +import React, { useContext, useEffect, useRef, useState } from 'react';
Move this React import back up

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/timetable/DropdownOption.tsx
> +import React from 'react';
Run prettier on this file

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/timetable/DroppedClass.tsx
> +                    <PeriodMetadata period={classCard} />
Use `&&` to replace this ternary for `isHideClassInfo`

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/controls/CustomEvents.tsx
> +import React, { useContext, useState } from 'react';
The file name should be the same as the component it is exporting. Pick one to change.

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/controls/CustomEvents.tsx
> +const CustomEvent = ({}) => {
Type this as `React.FC` just to be consistent. Also, empty argument list can just be denoted by `() => {}`, no need for the extra pair of braces.

2022-07-16 01:59 UTC, munjoonteo commented on client/src/components/timetable/Timetable.tsx
> +        {/* <DroppedClasses assignedColors={assignedColors} handleSelectClass={handleSelectClass} /> */}
Hmmmmmmmmmmm

2022-07-16 01:59 UTC, munjoonteo commented on client/src/context/AppContext.tsx
> +  setLatestEndTime: (newLatestEndTime: number) => void;
Newline here

2022-07-16 01:59 UTC, munjoonteo commented on client/src/interfaces/PropTypes.ts
> +import { ReactNode } from 'react';
Put React at the top

2022-07-16 01:59 UTC, munjoonteo commented on client/.gitignore
> +.npmrc
New line at end of file

2022-07-19 04:31 UTC, munjoonteo requested changes

2022-07-19 04:31 UTC, munjoonteo commented on client/package.json
> +    "mui-color": "^2.0.0-beta.2",
Make sure to uninstall this package

2022-07-19 04:31 UTC, munjoonteo commented on client/package.json
> +    "@types/date-fns": "2.6.0",
Uninstall this too

2022-07-19 04:31 UTC, munjoonteo commented on client/src/App.tsx
> +            Object.entries(course.activities).flatMap(([_, cs]) => cs.flatMap((c) => c.periods.map((p) => p.time.day)))
Can these variable names in these two `flatMap` and `map` statements be more descriptive too

2022-07-19 04:31 UTC, munjoonteo commented on client/src/components/timetable/DroppedCards.tsx
> +  // useEffect(() => {
Delete comment

2022-07-19 04:31 UTC, munjoonteo commented on client/src/App.tsx
> +  const daysOfTheWeek: string[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
Does it still work if you use the `weekdaysLong` declared in the timetable constants file?

2022-07-19 04:31 UTC, munjoonteo commented on client/src/App.tsx
> +        ...Object.entries(createdEvents).map(([_, val]) => val.time.start),
Would be nice to have more descriptive variable names instead of just `val`

2022-07-19 04:31 UTC, munjoonteo commented on client/src/App.tsx
> +        ...selectedCourses.map((course) => course.earliestStartTime),
It would be easier to read if these `map`s were assigned to a variable

2022-07-19 04:31 UTC, munjoonteo commented on client/src/components/controls/CustomEvent.tsx
> +  // const [color, setColor] = useState<ColorValue>('#1F7E8C');
Remember to delete these when you are done

2022-07-19 04:31 UTC, munjoonteo commented on client/src/components/controls/CustomEvent.tsx
> +          {/* <ListItem>
Remember to delete these when you are done

2022-07-19 04:31 UTC, munjoonteo commented on client/src/components/controls/CustomEvent.tsx
> +              Choose Color
Use the `colour` spelling

2022-07-19 04:31 UTC, munjoonteo commented on client/src/components/controls/CustomEvent.tsx
> +                  <Colorful onChange={(e) => setColor(e.hex)} color={color} />
Can there be an input field underneath this to allow the user to directly type in a hex code like before?

2022-07-19 04:31 UTC, munjoonteo commented on client/src/components/controls/CustomEvent.tsx
> +          <Box m={1} display="flex" justifyContent="center" alignItems="center">
The components inside this box should be vertically arranged instead of horizontally

2022-07-22 14:20 UTC, sssijin commented on client/src/App.tsx
> +            Object.entries(course.activities).flatMap(([_, cs]) => cs.flatMap((c) => c.periods.map((p) => p.time.day)))
uh sorry I currently do not have enough braincells to make them more descriptive rn

2022-07-23 05:01 UTC, merged