feature/NTGL-351: Backspace to delete courses from CourseSelect
csesoc/notangles pull request #503
Opened 2022-08-10 07:10 UTC by anjerraa

- added code in `CourseSelect.tsx` for deleting selected course when user backspace-ing.

2022-08-10 08:31 UTC, oliverxu42 approved these changes

2022-09-03 02:57 UTC, anjerraa commented
Please look again uwu @munjoonteo

2022-09-03 06:53 UTC, munjoonteo requested changes

2022-09-03 06:53 UTC, munjoonteo commented on client/src/components/controls/CourseSelect.tsx
> +              }
You haven't implemented undo yet

2022-09-03 07:40 UTC, munjoonteo approved these changes

2022-09-03 07:42 UTC, merged