Feature/NTGL-318: Convert To Local Timezone
csesoc/notangles pull request #510
Opened 2022-08-17 05:59 UTC by anjerraa

User can now convert the timetable to local timezone. It is available as a setting toggle (default is `True`).
* Timetable can account for half-an-hour timezone offsets.
* If a class goes over midnight (e.g. 11PM-1AM), it will show up as two cards, but manipulate one will manipulate the other (implemented in `DbCourse.ts`).
* Added `subActivity` as a field within `ClassPeriod` to be able to separate tutorials from laboratories (`subActivity` is the same as `activity` if the `activity` isn't 'Tutorial-Laboratory'). By separating tutorials and laboratories, we can correctly identify whether two periods are duplicates of each other (important for extended class view).
* In `timetable.ts`, the offset of local and Sydney timezones are calculated, and `getLocalTime()` is used to convert a given time to local time.
* If a timetable has an earliest start time less than latest end time, then the timetable layout will be displayed from that start to end times. If a timetable has a latest end time less than earliest start time, then the timetable goes over midnight, which will create a timetable layout from 12AM-12PM.

2022-08-17 06:26 UTC, oliverxu42 approved these changes

2022-08-27 06:34 UTC, zaxutic approved these changes
LGTM

2022-08-28 06:07 UTC, munjoonteo requested changes

2022-08-28 06:07 UTC, munjoonteo commented on client/src/utils/Drag.ts
> +// hello
lol

2022-08-28 06:07 UTC, munjoonteo commented on client/src/App.tsx
> -  // Populate selected courses, classes and created events with the data saved in local storage
Bring back this comment please

2022-08-28 06:07 UTC, munjoonteo commented on client/src/App.tsx
> -  // Update the bounds of the timetable (start time, end time, number of days) whenever a change is made to the timetable
Why u keep deleting my comments smh

2022-08-28 06:07 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +export const getTimeZoneOffset = (isConvertToLocalTimezone: boolean): number => {
Use the same format I did for the function documentation

2022-08-28 06:07 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +export const getLocalTime = (isConvertToLocalTimezone: boolean, time: number): number => {
Here too

2022-08-28 06:07 UTC, munjoonteo commented on client/src/components/timetable/TimetableLayout.tsx
> +  isConvertToLocalTimezone: boolean): string[] => {
Update function documentation

2022-08-28 10:36 UTC, anjerraa commented on client/src/App.tsx
> -  // Update the bounds of the timetable (start time, end time, number of days) whenever a change is made to the timetable
Bc u suck

2022-09-01 05:04 UTC, munjoonteo requested changes

2022-09-01 05:04 UTC, munjoonteo commented on client/src/App.tsx
> -          days.length, // Saturday and/or Sunday stays even if an event is moved to a weekday
Don't delete this. As per the comment, Sat/Sun should stay even if a custom event is dragged out of those days

2022-09-01 05:04 UTC, munjoonteo commented on client/src/components/navbar/Changelog.tsx
> +    date: 'August 17, 2022',
oop

2022-09-01 05:04 UTC, munjoonteo commented on client/src/components/timetable/TimetableLayout.tsx
> +      return Array(24)
Some duplicate code here. Could declare the `Array(24).fill(0)` outside the try/catch and populate its values as required.

2022-09-01 05:04 UTC, munjoonteo commented on client/src/constants/timetable.ts
> +  const offset = getTimeZoneOffset(isConvertToLocalTimezone);
I think it would be better if this was just `const offset = isConvertToLocalTimezone ? getTimeZoneOffset() : 0;`

2022-09-01 05:05 UTC, munjoonteo commented
Make sure you run prettier and fix merge conflicts

2022-09-02 05:22 UTC, munjoonteo approved these changes

2022-09-02 05:25 UTC, merged