Improve drag behavior regarding clashes
csesoc/notangles pull request #515
Opened 2022-08-19 12:00 UTC by martanman

fixes the width change of a card when it is placed on a clashing zone not having a transition but instead being instantaneous. It now transitions between the two widths as the already dropped classes do.

gets rid of behavior wherein the dragged card will stutter between two dropzones

![Peek 2022-08-19 21-54](https://user-images.githubusercontent.com/22385238/185613124-9dd4c219-439b-4a88-8f83-d35319d29d94.gif)

by making the dropzone calculation invariable from current card width size.

Now, width transition of the dragging card will shrink/grow towards/from the middle of the card rather than to/from the left side of the card.

2022-08-19 12:16 UTC, munjoonteo requested changes

2022-08-19 12:16 UTC, munjoonteo commented on client/src/App.tsx
> +          newSelectedCourseCodes.indexOf(course.name) === newSelectedCourseCodes.lastIndexOf(course.name) ||
What does this do

2022-08-19 12:16 UTC, munjoonteo commented on client/src/utils/Drag.ts
> +  const entryWidth = entries[0].contentRect.width;
According to this https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver this might not work in Firefox ? Or is it referring to something else ?

2022-08-20 06:09 UTC, martanman commented on client/src/App.tsx
> +          newSelectedCourseCodes.indexOf(course.name) === newSelectedCourseCodes.lastIndexOf(course.name) ||
in python pseudocode

`courses = list(set(courses))`

2022-08-20 06:15 UTC, martanman commented on client/src/utils/Drag.ts
> +  const entryWidth = entries[0].contentRect.width;
it says

> Firefox implements `contentBoxSize` as a single content rect, rather than an array

but I'm accessing `contentRect` not `contentBoxSize` so that's not it. plus if it were `Array<T> | T` would ts really just let me compile 🤷‍♂️

2022-08-20 06:25 UTC, munjoonteo approved these changes

2022-08-20 06:25 UTC, merged