Feature/ntgl 353 clone custom event
csesoc/notangles pull request #542
Opened 2022-09-03 09:38 UTC by sssijin

this branch allows users to clone an event that is already created

- is line 121 - 154 in ExpandedEventView too similar to the multiple event stuff in CustomEvents? do I need to store it as a function in somewhere else and then export it...

2022-09-03 13:11 UTC, munjoonteo commented
Can you make it so that if there's an event on multiple days, all the days are highlighted in the day picker? i.e. link the events that are created together.

Also idk if this is skill diff or not but I accidentally clicked the delete event button instead of save and I was sad.

2022-09-04 10:42 UTC, munjoonteo commented
Actually I take back the first point I said. But I find it a bit odd that after you clone an event and you click on it again, the days doesn't change.

2022-09-05 01:38 UTC, oliverxu42 commented
> 

Thoughts on making the "save changes" button at the bottom? Would be more consistent with the create event ui and avoid accidentally clicking delete. 
![image](https://user-images.githubusercontent.com/81744880/188343741-6dd36b0b-09b4-40fc-8f81-d5c39b35fae8.png)

2022-09-05 01:55 UTC, munjoonteo commented
> Thoughts on making the "save changes" button at the bottom? Would be more consistent with the create event ui and avoid accidentally clicking delete.

We could actually just remove the delete button from the editing screen and only show that button when you first click on an event. i.e. the only thing you can do in the edit menu is save or cancel. 

Moving the save button to the bottom would also be good.

2022-09-05 03:49 UTC, munjoonteo requested changes

2022-09-05 03:49 UTC, munjoonteo commented on client/src/components/timetable/ExpandedEventView.tsx
> +  const timePickerStart = (isChanged: boolean, newStartTime: Date, start: number) => {
What do these functions do? Can you add a JSDoc comment

2022-09-05 03:49 UTC, munjoonteo commented on client/src/components/timetable/ExpandedEventView.tsx
> +    const newEvent: EventPeriod = {
This function looks identical to the start of `createEvent` in `CustomEvent.tsx`. You can factor out the code to create a new `EventPeriod` to a function.

2022-09-05 12:39 UTC, sssijin commented on client/src/components/timetable/ExpandedEventView.tsx
> +    const newEvent: EventPeriod = {
donee

2022-09-05 12:39 UTC, sssijin commented on client/src/components/timetable/ExpandedEventView.tsx
> +  const timePickerStart = (isChanged: boolean, newStartTime: Date, start: number) => {
donee

2022-09-05 12:40 UTC, sssijin commented
> We could actually just remove the delete button from the editing screen and only show that button when you first click on an event. i.e. the only thing you can do in the edit menu is save or cancel.
> 
> Moving the save button to the bottom would also be good.

Have done both of the above

2022-09-06 03:57 UTC, munjoonteo approved these changes

2022-09-06 03:58 UTC, merged