Ntgl 361 custom event cant finish at 12 00 am
csesoc/notangles pull request #562
Opened 2022-09-15 08:16 UTC by sssijin

Custom events can now have an endtime at midnight

[ ] Did you want midnight to be expressed as 0:00 or 00:00 in the event card

2022-09-15 12:02 UTC, munjoonteo commented
Can you make it so that the values in the Create Event dropdown reset when the dropdown is closed?

2022-09-15 12:02 UTC, munjoonteo requested changes

2022-09-15 12:02 UTC, munjoonteo commented on client/src/utils/createEvent.ts
> +      end: endTime.getHours() + endTime.getMinutes() / 60 === 0 ? 24.0 : endTime.getHours() + endTime.getMinutes() / 60,
Can this be a variable

2022-09-15 23:58 UTC, oliverxu42 commented
> Custom events can now have an endtime at midnight
> 
> [ ] Did you want midnight to be expressed as 0:00 or 00:00 in the event card

00:00 should be fine

2022-09-18 03:30 UTC, munjoonteo approved these changes

2022-09-19 00:51 UTC, oliverxu42 approved these changes

2022-09-19 00:53 UTC, merged