Feature/friend support
csesoc/notangles pull request #575
Opened 2022-09-24 06:40 UTC by Rayahhhmed

The endpoints for the backend are done and can be checked with API documentation on confluence.

2022-09-24 13:02 UTC, munjoonteo requested changes

2022-09-24 13:02 UTC, munjoonteo commented on server/src/app.module.ts
> -    // AutoModule,
o.o

2022-09-24 13:02 UTC, munjoonteo commented on server/src/auth/auth.controller.ts
> +  @UseGuards(LoginGuard)
Nitpick here: all the examples I've seen have the GET/POST etc. decorator as the last line

2022-09-24 13:02 UTC, munjoonteo commented on server/src/auth/auth.service.ts
> +    const response = await this.userModel.findOne({ google_uid: uidGiven });
I noticed that you use `return await ...` a lot in your code. Can you make this one similar as well for consistency's sake

2022-09-24 13:02 UTC, munjoonteo commented on server/src/auth/auth.service.ts
>      sgMail
Could convert this to `async/await` too

2022-09-24 13:02 UTC, munjoonteo commented on server/src/database/database.module.ts
>  import { Module } from '@nestjs/common';
I think you forgot to delete this

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/dtos/friend.dto.ts
> +export class SingleFriendRequestDto {
You could probably just call this `FriendRequestDto`

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +  @Get('/:userId')
Same here

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +    const checkValidUser = async (uId: string) =>
Why didn't you declare this outside the function?

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/dtos/friend.dto.ts
> +  userId: string;
What do you think of the keys being called `senderId` and `sendeeId` instead? `userId` is a bit ambiguous until you realise that there's a `friendId` field

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +    if (!checkValidUser(body.userId) || !checkValidUser(body.friendId)) {
Could destructure `userId` and `friendId` here

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +    if (!checkValidUser(body.userId) || !checkValidUser(body.friendId)) {
Destructure here too

2022-09-24 13:02 UTC, munjoonteo commented on server/src/auth/auth.service.ts
> +          false,
Dark mode should be true by default ................

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +    if (!checkValidUser(body.userId) || !checkValidUser(body.friendId)) {
And here

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +    if (!checkValidUser(body.userId) || !checkValidUser(body.friendId)) {
And here

2022-09-24 13:02 UTC, munjoonteo commented on server/src/user/user.controller.ts
> +import { User } from '@sentry/node';
Extra import

2022-09-24 13:02 UTC, munjoonteo commented on server/src/user/user.controller.ts
> +  @Put('/timetable/:userId/:timetableId')
Redundant parameter `:timetableId`?

2022-09-24 13:02 UTC, munjoonteo commented on server/src/user/user.service.ts
> +    await this.deleteTimetable(userId, edittedTimetable.timetableId);
You could've just used `findOneAndUpdate` here... deleting and creating is kinda lazy

2022-09-24 13:02 UTC, munjoonteo commented on server/src/user/user.service.ts
> +    edittedTimetable: UserTimetablesDto,
There is only one t in edited

2022-09-24 13:02 UTC, munjoonteo commented on server/src/user/user.service.ts
> +      .exec();
Why do you use exec in some db calls but not others? Not criticising, just for my own knowledge

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +  async addFriend(@Body() body: SingleFriendRequestDto): Promise<User[]> {
Personally, I never explicitly specify the return types of functions because Typescript basically knows what it is already. I think it makes the lines too long.

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +     * There could be the case that the users are already
Ok these comments are literally telling a story and they're kinda not necessary

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +    const friended: boolean = await alreadyFriends(body.userId, body.friendId);
Always destructure your objects

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +        hasUserAsentReqToB(body.userId, body.friendId),
Why would both A and B need to send friend requests to each other ? Is it not just one-way?

2022-09-24 13:02 UTC, munjoonteo commented on server/src/friend/friend.controller.ts
> +  @Post('/request')
I feel like having POST /request should only be used to **send** a friend request. Then, PUT /request should be used to **accept** a friend request

2022-09-24 13:13 UTC, munjoonteo commented
A general comment about API design - a lot of your errors are simply ignored/sent to console. For example, `deleteFriendRequest` simply returns an empty array, and I assume a status code of 200, if a user is invalid. This is giving false information to the client. It should throw an error and thus return a 400 status code.

I also did some more reading about returning stuff after a POST/PUT/DELETE operation is successful, and it seems like the jury is pretty split on it. Some think that POST should return the object that was created. Some think that PUT should not return anything. A reminder to ask around and see what people think. The method I mentioned I was using for my thesis, namely not returning anything except 200 OK, is cleaner but has a big drawback - the client will have to re-fetch a lot of redundant information (e.g. for a POST, if only one object is created, re-fetching the previously created objects is a waste of bandwidth).

Your comments are also very extensive, which is good to see. But I believe Max has setup our backend to be self-documenting with the Swagger module provided by nest, so most of your personal comments are unnecessary. I get that this will take a while to write so I don't mind if you outsource writing documentation to me or something. It mostly involves defining the possible status codes that are returned by the endpoint and probably any query/path parameters. Body parameters are defined in the DTOs themselves.

2022-09-25 04:13 UTC, Rayahhhmed commented on server/src/friend/friend.controller.ts
> +        hasUserAsentReqToB(body.userId, body.friendId),
If A sent a friend req to B previously, and B is attempting to send one to A now (Basically accepting a friend req), they are added as friends and this data is removed from their individual collection.

2022-09-25 04:15 UTC, Rayahhhmed commented on server/src/database/database.module.ts
>  import { Module } from '@nestjs/common';
Shall I remove the entire database folder and files associated with it then? Cause I kinda need that import for the Decorator below

2022-09-25 04:25 UTC, munjoonteo commented on server/src/database/database.module.ts
>  import { Module } from '@nestjs/common';
Oh yeah I meant you forgot to delete this file

2022-10-01 07:25 UTC, munjoonteo approved these changes

2022-10-01 07:26 UTC, merged