Double click on timetable to create custom event
csesoc/notangles pull request #584
Opened 2022-10-01 14:35 UTC by manhualu

- User can double click anywhere on the timetable grid to create a custom event
- Temporary event with name '(No Title)' is created in position user double clicks on, deleted when user clicks out of Popover and deleted when user creates event with name
- When double clicked, a similar event popover appears, except day + startTime + endTime are pre-selected according to where they pressed on the grid
- Popover for create event code (when user double clicks + user clicks on Create Event in controls bar) is repeated because it got changed up by Angella's tutor support code, sorry MJ my brain too ded to fix up rn, T_T

2022-10-02 07:52 UTC, munjoonteo requested changes

2022-10-02 07:52 UTC, munjoonteo commented on client/src/interfaces/PropTypes.ts
> +  isDoubleClicked: boolean;
What's the point of this `isDoubleClicked` prop?

2022-10-08 02:01 UTC, manhualu commented on client/src/interfaces/PropTypes.ts
> +  isDoubleClicked: boolean;
oop yea this was used for when I had one event popover that appears both when manually creating an event and double clicking, but then with Angella's tutor support code I had to remove it.

2022-10-22 05:24 UTC, munjoonteo requested changes

2022-10-22 05:24 UTC, munjoonteo commented on client/src/components/controls/ColorPicker.tsx
> +      <ColourIndicatorBox backgroundColour={color} />
Can you make it so that the colour picker also opens when you click the colour indicator box

2022-10-22 05:24 UTC, munjoonteo commented on client/src/components/timetable/DoubleClickedCreateEventPopover.tsx
> +  const colorPickerPopoverId = openColorPickerPopover ? 'simple-popover' : undefined;
I don't think we need this Id variable

2022-10-22 05:24 UTC, munjoonteo commented on client/src/components/controls/CustomEvent.tsx
> +  const popoverId = openCreateEventPopover ? 'simple-popover' : undefined;
I don't think we need this id variable

2022-10-22 05:24 UTC, munjoonteo commented on client/src/components/timetable/DoubleClickedCreateEventPopover.tsx
> +          setIsInitialDay={setIsInitialDay}
lmao (not hating just funny)

2022-10-22 05:24 UTC, munjoonteo commented on client/src/components/navbar/Changelog.tsx
> +    date: 'October 1, 2022',
gg

2022-10-29 06:15 UTC, munjoonteo approved these changes

2022-10-29 06:16 UTC, merged