Feature/ntgl 386 clear timetable
csesoc/notangles pull request #669
Opened 2023-03-02 08:43 UTC by jasttran

- re-implemented 'reset timetable' to completely clear the timetable
- changed the icon to be a trash can and the tooltip to 'Clear(Ctrl+D)'
- implemented Ctrl+d hotkey to clear the timetable
- undo and redo actions still works on clearing the timetable
- clear timetable button is disabled when the timetable is empty

2023-03-08 12:43 UTC, manhualu commented on client/src/components/controls/History.tsx
> +    (nCourses === 0 && nEvents === 0 && nClasses === 0) ? setDisableReset(true) : setDisableReset(false);
This could be reduced to: setDisableReset(nCourses === 0 && nEvents === 0 && nClasses === 0)

2023-03-08 13:04 UTC, manhualu commented on client/src/components/controls/History.tsx
>    const restoreInitial = () => {
Might be a good idea to change the name from restoreInitial to clearAll or something else

2023-03-08 13:09 UTC, manhualu requested changes
Also like with every new feature implemented, please add this new feature into the ChangeLog file : )

2023-03-10 01:10 UTC, manhualu commented
regarding Ollie's message on Discord, can you also change the year from 2022 to 2023 in the About.tsx file before you merge : )

2023-03-13 14:22 UTC, manhualu approved these changes

2023-03-13 14:33 UTC, Rayahhhmed commented
Congrats you two :)

2023-03-13 14:35 UTC, Rayahhhmed approved these changes

2023-03-13 14:35 UTC, merged