Feature/ntgl 394 updated link sharing
csesoc/notangles pull request #744
Opened 2023-06-29 02:21 UTC by incalescence

- Link sharing works with copying and pasting url!
- Currently the code is still on localhost:3000, needs to be updated before deployment

2023-09-01 13:45 UTC, manhualu requested changes, later dismissed

2023-09-01 13:45 UTC, manhualu commented on client/src/components/timetable/ExpandedEventView.tsx
> +  const url = 'localhost:3000/event/' + btoa(JSON.stringify(eventPeriod));
will this work with the hardcoded 'localhost:3000' url when we deploy it?

2023-09-01 13:45 UTC, manhualu commented on client/src/components/timetable/ExpandedEventView.tsx
> +  const url = 'localhost:3000/event/' + btoa(JSON.stringify(eventPeriod));
I think you'll have to get the current URL of the webpage

2023-09-01 13:45 UTC, manhualu commented on client/src/components/timetable/ExpandedEventView.tsx
> +  const url = 'localhost:3000/event/' + btoa(JSON.stringify(eventPeriod));
should be able to do something like: 
```suggestion
const currentUrl = window.location.href;
const url = currentUrl + 'event/' + btoa(JSON.stringify(eventPeriod));
```

2023-09-01 13:45 UTC, manhualu commented on client/src/components/EventShareModal.tsx
> +    setEarliestStartTime(Math.min(Math.floor(earliestStartTime), Math.floor(startTime)));
these lines of code is also used in the CustomEvent.tsx file, can you put it into a function?

2023-09-01 13:45 UTC, manhualu commented on client/src/components/EventShareModal.tsx
> +    if (day == 5 || day == 6) {
put this in a shared file as well to use in CustomEvent.tsx

2023-10-26 08:07 UTC, manhualu commented
@incalescence should we support multiple timetables for the adding of the event? As right now the user can only place an event on their first default timetable

2023-10-26 08:33 UTC, Rayahhhmed commented on client/src/components/controls/CustomEvent.tsx
> +    if (daysShort.indexOf(day) == 5 || daysShort.indexOf(day) == 6) {
Any reason why === wasnt used here?

2023-10-26 08:34 UTC, Rayahhhmed commented on client/src/components/controls/CustomEvent.tsx
> +            (eventType === 'Tutoring' && (courseCode === '' || classCode === ''))
All of these values are faulty code can be cleaned up using their boolean values ie
(eventType === 'General' && (!eventName || ...))

2023-10-26 08:36 UTC, manhualu commented on client/src/components/controls/CustomEvent.tsx
> +            (eventType === 'Tutoring' && (courseCode === '' || classCode === ''))
damn this was past me 💀, will fix

2023-10-26 08:37 UTC, manhualu commented on client/src/components/controls/CustomEvent.tsx
> +            (eventType === 'Tutoring' && (courseCode === '' || classCode === ''))
also just realised this does not implement location is optional 🤔 (merging dev messed up)

2023-10-26 08:38 UTC, Rayahhhmed commented on client/src/components/controls/CustomEvent.tsx
> +            (eventType === 'Tutoring' && (courseCode === '' || classCode === ''))
issokay i forgive u
but next time i shout coffee (or tea) if u stuff up

2023-10-26 08:48 UTC, Rayahhhmed commented
> @incalescence should we support multiple timetables for the adding of the event? As right now the user can only place an event on their first default timetable

How should this be, like the user then gets to decide which timetable this event gets placed on? 
Like they can select all or select couple ? that will be cool
Like a modal that pops up and they get to pick which timetable the event is at.

2023-10-26 08:59 UTC, manhualu approved these changes

2023-10-26 09:05 UTC, Rayahhhmed approved these changes

2023-10-26 09:05 UTC, merged