Feature/ntgl 404 persisting prev data
csesoc/notangles pull request #792
Opened 2023-11-13 11:42 UTC by Shzmj

Give the users the ability to view old terms data when required. 

Use case: Say when T3 timetables are released and it is still T2, users may want to see T2 timetable.

<img width="1455" alt="image" src="https://github.com/csesoc/notangles/assets/109339363/ccc33e60-41c0-428d-aff9-4c936f146abc">

- fixed timeout issues with course selector
- fixed history handling with multiple terms and timetables
- forced horizontal dragging of timetable tabs

2023-12-04 10:28 UTC, Shubh141 commented
Looks good Jaam Shevan!

2023-12-04 10:31 UTC, jeremyle56 commented
This is my ticket!

2024-03-28 10:17 UTC, Rayahhhmed requested changes

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/api/getCourseInfo.ts
> +    const data = await timeoutPromise(2000, fetch(`${baseURL}/courses/${courseCode}/`));
Change to a configuration variable

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/components/EventShareModal.tsx
> +import { useNavigate, useParams } from 'react-router-dom';
Rearrange imports alphabetically

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/components/timetableTabs/TimetableTabs.tsx
> +    const rearrangedTimetables = {
Thoughts on putting a type for  this

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/constants/timetable.ts
> +  if (matched != null) {
Weak typing ? Why is it like this

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/constants/timetable.ts
> +    const prevTermDate = await timeoutPromise(1000, fetch(`${API_URL.timetable}/startdate/freerooms`));
I don't like us calling freerooms path make a new Pr for a generic path

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/interfaces/Periods.ts
> +  term: string,
Term n term name is extra pick one n have a function to figure out the other

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/App.tsx
> +      const newTimetableTerms = {
Put a type for this

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/App.tsx
> +        ...({ [termsData.prevTerm.term]: oldData.hasOwnProperty(termsData.prevTerm.term) ? oldData[termsData.prevTerm.term] : createDefaultTimetable() }),
Is it always guaranteed the field `term` is non null / undefined? Cause otherwise will cause some serious problems.
The docs says `hasOwnProperty` only checks for fields and not their values, doing a check for nullity might be a good way to prevent errors. 
Bruh null in the codebase is so doomed.,

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/App.tsx
> +        ...({ [termsData.prevTerm.term]: oldData.hasOwnProperty(termsData.prevTerm.term) ? oldData[termsData.prevTerm.term] : createDefaultTimetable() }),
Maybe we might have a cleaning up / refactoring  ticket where we convert the nulls to undefined?

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/components/controls/History.tsx
> +    const newDisplayTimetables = {
Types here too

2024-03-28 10:17 UTC, Rayahhhmed commented on client/src/interfaces/Periods.ts
> +}
add newline

2024-04-02 14:36 UTC, jeremyle56 commented on client/src/components/EventShareModal.tsx
> +import { useNavigate, useParams } from 'react-router-dom';
@Rayahhhmed I believe the `eslint` configuration sorts imports by the library/module they are from. As such this sorting is correct based from the current config. Consider changing the config if this is unwanted behavior.

The following code is found in `.eslintrc.js` and the corressponding documentation can be found [here](https://github.com/lydell/eslint-plugin-simple-import-sort#sorting).
```js
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error',
```

2024-05-13 11:47 UTC, Rayahhhmed approved these changes

2024-05-14 12:08 UTC, merged