Feature: Added faculty filtering to search bar (Search bar Redesign #818)
csesoc/notangles pull request #838
Opened 2024-06-04 06:48 UTC by chanboba

* added the ability to filter course by faculty 
* added a facultyName map to map the fetched faculty names to our stored names
* added deselecting functionality to the filter buttons
* ensured same area of study filtering only applies when no faculty is selected

![image](https://github.com/devsoc-unsw/notangles/assets/112926046/e35b8441-f95c-4e51-abe6-47c7aadb9f10)

![image](https://github.com/devsoc-unsw/notangles/assets/112926046/ffc49996-d1c4-444a-9c1b-94356976348e)

2024-06-06 05:23 UTC, Rayahhhmed requested changes

2024-06-06 05:23 UTC, Rayahhhmed commented on client/src/components/controls/CourseSelect.tsx
> +    setSelectedFaculty(selectedFaculty == faculty ? "" : faculty);
nit: ``===`` please

2024-06-06 05:23 UTC, Rayahhhmed commented on client/src/interfaces/Courses.ts
> +}
nit: add a new line

2024-06-06 05:23 UTC, Rayahhhmed commented on client/src/components/controls/CourseSelect.tsx
> +export default CourseSelect;
nit: add a new line

2024-06-06 05:53 UTC, Rayahhhmed commented on client/src/components/controls/CourseSelect.tsx
> +  const faculties = ["Art, Design & Architecture", "Law & Justice", "Medicine & Health", "Engineering", "Business School", "Science"];
double ""

2024-06-11 10:09 UTC, Shzmj requested changes

2024-06-11 10:09 UTC, Shzmj commented on client/src/components/controls/CourseSelect.tsx
> +              </Button>
can we create a styled component for this to avoid inline styling plspsls

2024-06-14 01:25 UTC, Rayahhhmed approved these changes
clgtm

2024-06-14 01:35 UTC, Shzmj approved these changes

2024-06-14 01:36 UTC, merged