user and friend endpoints
csesoc/notangles pull request #851
Opened 2024-06-21 04:54 UTC by M7s7

This PR adds user and friend endpoints and the related test suite.

2024-08-29 10:06 UTC, Rayahhhmed approved these changes

2024-08-29 10:06 UTC, Rayahhhmed commented
amazing job king

2024-08-29 11:26 UTC, Shzmj requested changes

2024-08-29 11:26 UTC, Shzmj commented on server/prisma/schema.prisma
> +  // userID          String
oop can we remove these comments

2024-08-29 11:26 UTC, Shzmj commented on server/prisma/schema.prisma
> +// }
oop can we remove these comments if not needed anymore

2024-08-29 11:26 UTC, Shzmj commented on server/src/user/dto/timetable.dto.ts
> +  times: any[]; // Change later but im lazy
can we define proper type for this

2024-08-29 11:26 UTC, Shzmj commented on server/test/db.spec.ts
> +    // });expect(res.status).not.toEqual(201);
can you check whats wrong with this test case

2024-08-29 11:26 UTC, Shzmj commented on server/test/db.spec.ts
> +    // });
check whats wrong with the edge cases

2024-08-30 01:11 UTC, Shzmj approved these changes

2024-08-30 01:11 UTC, Shzmj commented
ready to merge 🙈

2024-08-31 08:34 UTC, merged