Staging Changes
csesoc/notangles pull request #855
Opened 2024-07-01 07:23 UTC by Rayahhhmed

* Cleaned up auth redirects to be dependent on Environment.
* Cleaned up auth comments on the referencing bugs.
* Merging in @hhuolu 's Logout dialogue.
* Auth users added to Database and db integrity finalised for addition of new users.

2024-07-01 07:37 UTC, lhjt approved these changes

2024-07-01 07:37 UTC, lhjt commented on .github/workflows/ci.yml
I am assuming the changes to this file are intentional and u know what ur doing

2024-07-01 08:17 UTC, Shzmj requested changes

2024-07-01 08:17 UTC, Shzmj commented on server/src/auth/auth.service.ts
> +      console.log(this.configService.get<string>('app.redirectLink'));
debug print statement still here

2024-07-01 08:17 UTC, Shzmj commented on server/src/auth/auth.controller.ts
> +        console.debug(`User ${userID} does not exist in db, adding them now!`);
remove debugging statements

2024-07-01 08:17 UTC, Shzmj commented on client/src/components/sidebar/UserAccount.tsx
> +              {/* TODO: error handling for when logging out */}
are the todos intentional i.e. will it be implemented in the future?

2024-07-02 04:54 UTC, Rayahhhmed commented on server/src/auth/auth.service.ts
> +      console.log(this.configService.get<string>('app.redirectLink'));
o this is legit error

2024-07-02 04:54 UTC, Rayahhhmed commented on server/src/auth/auth.controller.ts
> +        console.debug(`User ${userID} does not exist in db, adding them now!`);
Nah need this for dev logs debugging

2024-07-02 04:54 UTC, Rayahhhmed commented on client/src/components/sidebar/UserAccount.tsx
> +              {/* TODO: error handling for when logging out */}
Todos necessary for future

2024-07-08 00:44 UTC, Shzmj approved these changes

2024-07-11 04:56 UTC, merged