Feature/ntgl 820 friend group
csesoc/notangles pull request #877
Opened 2024-08-31 03:26 UTC by jasttran

Friend Features:
- see friends list and can remove friends
- see incoming friend requests
- search for users and send friend requests

Group Features:
- can create a group with friends.
- admins can edit/delete groups
- members can leave groups

2024-09-10 05:24 UTC, Rayahhhmed requested changes

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/App.tsx
>        Object.keys(course.activities).forEach((activity) => {
break this code into functions, very hard to read oops

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/components/sidebar/Sidebar.tsx
>    // TODO: dummy logic to be
wats this TODO? Could you remove it :D

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/components/sidebar/groupsSidebar/AddOrEditGroupDialogContent.tsx
> +    console.log('groupp', group);
remove clg

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/components/sidebar/groupsSidebar/AddOrEditGroupDialogContent.tsx
> +      setErrorMessage(InputError.GROUP_NAME);
rlly good code here with the enums

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/components/sidebar/groupsSidebar/friends/YourFriendsTab.tsx
> +const YourFriendsTab: React.FC<{ user: User | undefined; getUserInfo: () => void }> = ({ user, getUserInfo }) => {
sadly dont have any

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/components/sidebar/groupsSidebar/friends/YourFriendsTab.tsx
> +      //   if (res.status !== 200) throw new NetworkError("Couldn't get response");
is this comment supposed to be here

2024-09-10 05:24 UTC, Rayahhhmed commented on client/src/components/sidebar/groupsSidebar/friends/YourFriendsTab.tsx
> +    try {
would a function like 3900 help here?

2024-09-10 05:24 UTC, Rayahhhmed commented on server/src/user/user.service.ts
> +        delete group.members;
`delete` is a scary keyword, what is this supposed to do?

2024-09-10 23:22 UTC, jasttran commented on client/src/components/sidebar/Sidebar.tsx
>    // TODO: dummy logic to be
not sure it was there before, but i shall remove its existence 🫡

2024-09-10 23:29 UTC, jasttran commented on client/src/components/sidebar/groupsSidebar/friends/YourFriendsTab.tsx
> +      //   if (res.status !== 200) throw new NetworkError("Couldn't get response");
yeah thanks i uncommented it

2024-09-10 23:35 UTC, jasttran commented on server/src/user/user.service.ts
> +        delete group.members;
the `delete` keyword is used to remove properties from an object. This is a JavaScript feature that allows you to modify an object by removing specific keys.

This part of the code is removing the members, groupAdmins, and timetables properties from the group object.

This gets removed in ticket #880 though.

2024-09-10 23:35 UTC, jasttran commented on client/src/components/sidebar/groupsSidebar/friends/YourFriendsTab.tsx
> +    try {
yeah it would

2024-09-10 23:36 UTC, jasttran commented on client/src/App.tsx
>        Object.keys(course.activities).forEach((activity) => {
ermm I might need help on this, cuz I don't really know what you mean

2024-09-21 06:05 UTC, Rayahhhmed approved these changes

2024-09-22 14:51 UTC, Shzmj approved these changes
AMAZING WORK 🚀. 
Nit: console.log statements within a few files (AddAFriendTab, RequestsTab) for response status -> maybe we would need these when we do final testing for friends system? @Rayahhhmed

2024-09-22 22:25 UTC, Rayahhhmed commented
@jasttran  run a final lint as well before u push
We can have a logger installed to mitigate this @Shzmj  so during prod we don't see dev console logs. I will look into it!

2024-09-23 02:42 UTC, merged