Update of setup docs
csesoc/notangles pull request #928
Opened 2024-12-24 11:13 UTC by marktran2

Extra details for the setup documentation for a smoother experience for others.

2025-02-22 07:40 UTC, mark-trann commented
Closing this (not priority rn)

2025-04-13 23:06 UTC, lhvy requested changes

2025-04-13 23:06 UTC, lhvy commented on client/README.md
>  - npm v8.3.1
Let's change this to pnpm 10 and Node 22

2025-04-13 23:06 UTC, lhvy commented on server/README.md
> +$ docker-compose up
This causes problems (at least on WSL) where the Docker version of the Notangles server is brought up too, taking port 3001 without hot reloading. Might need to work out a better way to do this...

2025-05-23 03:09 UTC, lhvy approved these changes

2025-05-23 03:10 UTC, merged